# Generated by Django 4.2 on 2023-04-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.IntegerField(choices=[(-2, '😡'), (-1, '🙁'), (0, '😐'), (1, '🙂'), (2, '😀')])),
                ('pontualidade', models.IntegerField(choices=[(-2, '😡'), (-1, '🙁'), (0, '😐'), (1, '🙂'), (2, '😀')])),
                ('qualidade', models.IntegerField(choices=[(-2, '😡'), (-1, '🙁'), (0, '😐'), (1, '🙂'), (2, '😀')])),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=6),
        ),
    ]
